%% 数据预处理
clear;
a = load('C:\Users\admin\Desktop\组会\2024.4.29\fg_ng_mcn\4-8\fg_1_time.mat');
b = load('C:\Users\admin\Desktop\组会\2024.4.29\fg_ng_mcn\4-8\ng_1_time.mat');

% 数据转换
a1 = cell(1,10); b1 = cell(1,10);
for i = 1:10
    for j = 1:5
        a1{1,i}{1,j} = mean(a.time1{1,i}{1,j});
        b1{1,i}{1,j} = mean(b.time1{1,i}{1,j});
    end
end

a2 = zeros(10,5); b2 = zeros(10,5);
for i = 1:10
    for j = 1:5
        a2(i,j) = a1{1,i}{1,j};
        b2(i,j) = b1{1,i}{1,j};
    end
end

%% 高对比度配色方案 (Paul Tol's vibrant palette)
color = struct(...
    'blue',    [0   0.6   1],...   % 亮蓝色 (HEX: #0099FF)
    'orange',  [1   0.4   0],...   % 橙红色 (HEX: #FF6600)
    'grid',    [0.96 0.96 0.96],...% 极浅灰背景
    'text',    [0.2 0.2 0.2],...   % 深灰文本
    'sig',     [0.3 0.3 0.3]...    % 显著性标记色
);

%% 可视化参数
params = struct(...
    'box_width',     0.18,...       % 箱线图宽度
    'scatter_size',  36,...         % 散点尺寸
    'jitter',        0.08,...       % 点分布随机性
    'line_width',    1.8,...        % 箱线边框粗细
    'sig_font',      18 ...         % 显著性星号字号
);

%% 生成可视化
figure('Color','w','Position',[100 100 800 550]);
hold on;

% 箱线图绘制
boxplot(a2, 'Positions',1:5,...
    'Widths', params.box_width,...
    'Colors', color.blue,...
    'Symbol','+',...
    'Whisker',1.5);

boxplot(b2, 'Positions',(1:5)+0.3,...
    'Widths', params.box_width,...
    'Colors', color.orange,...
    'Symbol','+',...
    'Whisker',1.5);

% 散点图层
for j = 1:5
    % FG组散点
    x_jitter = j + (rand(10,1)-0.5)*params.jitter;
    scatter(x_jitter, a2(:,j), params.scatter_size,...
        'MarkerFaceColor', color.blue,...
        'MarkerEdgeColor', color.blue*0.6,...
        'LineWidth',1.2,...
        'MarkerFaceAlpha',0.7);
    
    % NG组散点
    x_jitter = j+0.3 + (rand(10,1)-0.5)*params.jitter;
    scatter(x_jitter, b2(:,j), params.scatter_size,...
        'MarkerFaceColor', color.orange,...
        'MarkerEdgeColor', color.orange*0.6,...
        'LineWidth',1.2,...
        'MarkerFaceAlpha',0.7);
end

%% 显著性标记 (自动定位)
sig_groups = 2; % 需要标记的组号

for group = sig_groups
    % 计算箱体中心坐标
    box_centers = [group, group+0.3];
    
    % 动态确定标记高度
    y_pos = max([a2(:,group); b2(:,group)]) + 0.025;
    
    % 绘制显著性线
    line(box_centers, [y_pos y_pos],...
        'Color', color.sig,...
        'LineWidth', params.line_width,...
        'LineJoin','round');
    
    % 添加星号
    text(mean(box_centers), y_pos + 0.015,...
        '*',...
        'FontSize', params.sig_font,...
        'HorizontalAlignment', 'center',...
        'Color', color.sig);
end

%% 图表修饰
set(gca,...
    'FontName', 'Arial',...
    'FontSize', 11,...
    'XTick', (1:5)+0.15,...
    'XTickLabel', {'MS1','MS2','MS3','MS4','MS5'},...
    'YLim', [0.45 0.75],...
    'Box', 'off',...
    'GridColor', color.grid,...
    'GridAlpha', 0.4);

ylabel('Temporal Variability',...
    'FontSize', 12,...
    'FontWeight', 'bold',...
    'Color', color.text);

legend({'FG','NG'},...
    'Location', 'northeast',...
    'Box', 'off',...
    'EdgeColor', color.grid,...
    'FontSize', 10);

% 网格系统
grid on;
ax = gca;
ax.XGrid = 'on';
ax.YGrid = 'on';
ax.Layer = 'top';
ax.GridLineStyle = '-';

hold off;